learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
    path('login/', include('guest_user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_log/learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.urls import path, include
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path(
        'remove_topic/<int:topic_id>/', views.remove_topic, name='remove_topic'
    ),
    path(
        'remove_entry/<int:entry_id>/<int:topic_id>',
        views.remove_entry,
        name='remove_entry'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

learning_log/users/urls.py
"""Определяет схемы URL для пользователей."""
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = 'users'
urlpatterns = [
     path('register/', views.register, name='register'),
     path('login/', auth_view.LoginView.as_view(
          redirect_authenticated_user=True),
          name='login'
          ),
     path(
          'password_change/',
          auth_view.PasswordChangeView.as_view(
               success_url=reverse_lazy(
                    'users:password_change_done'
               ), template_name='password/password_change_form.html'
          ), name='password_change'
     ),
     path('profile/', views.profile, name='profile'),
     path('', include('django.contrib.auth.urls')),
     path(
          'password_change_done/',
          auth_view.PasswordChangeDoneView.as_view(
               template_name='password/password_change_done.html'
          ), name='password_change_done'
     ),
     path(
          'reset_password/',
          auth_view.PasswordResetView.as_view(
               template_name='password/password_reset_form.html',
               email_template_name='password/password_reset_email.html',
               success_url=reverse_lazy(
                    'users:password_reset_done'
               )
          ), name='reset_password'
     ),
     path(
          'reset_password_sent/',
          auth_view.PasswordResetDoneView.as_view(
               template_name='password/password_reset_done.html'
          ), name='password_reset_done'
     ),
     path(
          'reset/<uidb64>/<token>',
          auth_view.PasswordResetConfirmView.as_view(
               success_url=reverse_lazy(
                    'users:password_reset_complete'
               ), template_name='password/password_reset_confirm.html'
          ), name='password_reset_confirm'
     ),
     path(
          'reset_password_complete/',
          auth_view.PasswordResetCompleteView.as_view(
               template_name='password/password_reset_complete.html'
          ), name='password_reset_complete'
     )
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = RichTextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) >= 50:
            return f'{self.text[:50]}...'
        else:
            return f'{self.text[:50]}'

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import logout
from guest_user.decorators import allow_guest_user
from guest_user.functions import is_guest_user
from .forms import TopicForm, EntryForm
from .models import Topic, Entry


def index(request):
    return render(request, 'learning_logs/index.html')


@allow_guest_user
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')

    check_topic_owner(topic.owner, request.user)

    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    if not request.POST:
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    if is_guest_user(request.user):
        logout(request)
        return redirect('users:login')

    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)

    if not request.POST:
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    if is_guest_user(request.user):
        logout(request)
        return redirect('users:login')

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic.owner, request.user)

    if not request.POST:
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def remove_topic(request, topic_id):
    if is_guest_user(request.user):
        logout(request)
        return redirect('users:login')

    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)

    Topic.objects.filter(id=topic_id).delete()

    return redirect('learning_logs:topics')


@login_required
def remove_entry(request, entry_id, topic_id):
    if is_guest_user(request.user):
        logout(request)
        return redirect('users:login')

    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)

    Entry.objects.filter(id=entry_id).delete()

    return redirect('learning_logs:topic', topic.id)


def check_topic_owner(owner, user):
    if owner != user:
        raise PermissionDenied

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-wirdt, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">Learning Log</a>
  
      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Topics</a></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
    </nav>
  
    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
  
  <footer class="blog-footer" 
  style="padding: 2.5rem 0;
    color: #999;
    text-align: center;
    background-color: #f9f9f9;
    border-top: .05rem solid #e5e5e5;
    ">
    <p style="margin-bottom: 0;">The application is written by
      <a href="https://gitlab.com/MakeHate">Yagami Light</a>.</p>
  </footer>
  </body>
  
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{{ content|safe }}

{% block page_header %}
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    <p>Edit entry:</p>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the topics
        you're learning about. Whenever you learn something new about a topic,
        make an entry summarizing what you've learned. When you go to the topics tab, 
        you will be automatically logged in under the guest profile to familiarize yourself 
        with the functionality.</p>

    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
        role="button">Begin &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    Add a new entry in: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <p>Add a new topic:</p>
{% endblock page_header %}


{% block content %}

    <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <div>
    <h3>{{ topic }}</h3>
    <button class="btn btn-primary float-right" style="background: #DCDCDC; margin-top:-38px">
      <small><a href="{% url 'learning_logs:remove_topic' topic.id %}">Remove topic</a></small>
  </div>
{% endblock page_header %}

{% block content %}
<p>
  <div>
    <button class="btn btn-primary" style="background: #DCDCDC">
      <small><a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a></small>
  </div>
</p>

{% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      <img src="{{ user.profile.image.url }}" alt='Аватарка' decoding='sync' width="50" height="50">
      {{ entry.date_added|date:'M d, Y H:i'}}
        <button class="btn btn-primary float-right" style="background: #DCDCDC">
            <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></small>
        <button class="btn btn-primary float-right" style="background: #DCDCDC; margin-right:10px">
            <small><a href="{% url 'learning_logs:remove_entry' entry.id topic.id %}">Remove entry</a></small>
    </h4>
    {{ entry.text|safe }}  
  </div>  
{% empty %}
  <p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
  <button class="btn btn-primary float-right" style="background: #DCDCDC; margin-top: -50px">
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}
  </ul>

{% endblock content %}