learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
    path('login/', include('guest_user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_log/learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.urls import path, include
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path(
        'remove_topic/<int:topic_id>/', views.remove_topic, name='remove_topic'
    ),
    path(
        'remove_entry/<int:entry_id>/<int:topic_id>',
        views.remove_entry,
        name='remove_entry'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

learning_log/users/urls.py
"""Определяет схемы URL для пользователей."""
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = 'users'
urlpatterns = [
     path('register/', views.register, name='register'),
     path('login/', auth_view.LoginView.as_view(
          redirect_authenticated_user=True),
          name='login'
          ),
     path(
          'password_change/',
          auth_view.PasswordChangeView.as_view(
               success_url=reverse_lazy(
                    'users:password_change_done'
               ), template_name='password/password_change_form.html'
          ), name='password_change'
     ),
     path('profile/', views.profile, name='profile'),
     path('', include('django.contrib.auth.urls')),
     path(
          'password_change_done/',
          auth_view.PasswordChangeDoneView.as_view(
               template_name='password/password_change_done.html'
          ), name='password_change_done'
     ),
     path(
          'reset_password/',
          auth_view.PasswordResetView.as_view(
               template_name='password/password_reset_form.html',
               email_template_name='password/password_reset_email.html',
               success_url=reverse_lazy(
                    'users:password_reset_done'
               )
          ), name='reset_password'
     ),
     path(
          'reset_password_sent/',
          auth_view.PasswordResetDoneView.as_view(
               template_name='password/password_reset_done.html'
          ), name='password_reset_done'
     ),
     path(
          'reset/<uidb64>/<token>',
          auth_view.PasswordResetConfirmView.as_view(
               success_url=reverse_lazy(
                    'users:password_reset_complete'
               ), template_name='password/password_reset_confirm.html'
          ), name='password_reset_confirm'
     ),
     path(
          'reset_password_complete/',
          auth_view.PasswordResetCompleteView.as_view(
               template_name='password/password_reset_complete.html'
          ), name='password_reset_complete'
     )
]

learning_log/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

learning_log/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserCreateForm, UserUpdateForm, ProfileUpdateForm
from guest_user.functions import is_guest_user


def register(request):
    user_auth = request.user.is_authenticated

    if not user_auth:
        if not request.POST:
            form = UserCreateForm()
        else:
            form = UserCreateForm(data=request.POST)

            if form.is_valid():
                new_user = form.save()
                login(request, new_user)
                return redirect('learning_logs:index')
    else:
        return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)


@login_required
def profile(request):
    if is_guest_user(request.user):
        logout(request)
        return redirect('users:login')

    if not request.POST:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    else:
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Ваш профиль успешно обновлен.')

            return redirect('users:profile')

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, 'registration/profile.html', context)

learning_log/users/templates/password/password_change_done.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <form method="post" action="{% url 'users:password_change_done' %}" class="form">
      {% csrf_token %}
      <h1>Password changed</h1>
      <p>Your password has been successfully changed.</p>
    </form>
{% endblock %}

learning_log/users/templates/password/password_change_form.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Change your password.</h2>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'users:password_change' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Change password</button>
    {% endbuttons %}

    <input type="hidden" name="next"
      value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

learning_log/users/templates/password/password_reset_complete.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Reset complete</h2>
  <p>Your password has been set. You may go ahead and log in now.</p>
{% endblock page_header %}

{% block content %}
  <form action="{{ login_url }}">
    {% csrf_token %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_log/users/templates/password/password_reset_confirm.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Password reset confirmation.</h2>
{% endblock page_header %}

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

{% block content %}
{% if validlink %}
  <form method="post" action="{% url 'users:password_change' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Change password</button>
    {% endbuttons %}

    <input type="hidden" name="next"
      value="{% url 'learning_logs:index' %}" />
  </form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}

{% endblock content %}

learning_log/users/templates/password/password_reset_done.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
  <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock page_header %}

learning_log/users/templates/password/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

learning_log/users/templates/password/password_reset_form.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Password Reset</h2>
  <p>Forgotten your password? Enter your email address below, and well email instructions for setting a new one.</p>
{% endblock page_header %}

{% block content %}
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Change password</button>
    {% endbuttons %}
  </form>

{% endblock content %}